name: Publish

on:
  push:
    branches: ['main']

permissions: write-all

jobs:
  qemu:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-latest-xlarge]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: "Setup Rust"
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: nightly
          components: clippy
      - name: Download circom (Linux)
        if: ${{ matrix.os == 'ubuntu-latest'}}
        run: wget https://github.com/iden3/circom/releases/latest/download/circom-linux-amd64 -O /usr/local/bin/circom && chmod +x /usr/local/bin/circom
      - name: Download circom (Windows)
        if: ${{ matrix.os == 'windows-latest'}}
        run: curl https://github.com/iden3/circom/releases/latest/download/circom-windows-amd64.exe -o C:\Windows/circom && icacls C:\Windows/circom /grant Everyone:RX
      - name: Download circom (Macos)
        if: ${{ matrix.os == 'macos-latest'}}
        run: curl https://github.com/iden3/circom/releases/latest/download/circom-macos-amd64 -o /usr/local/bin/circom && chmod +x /usr/local/bin/circom
      - name: Download circom (Macos ARM64)
        if: ${{ matrix.os == 'macos-latest-xlarge'}}
        run: curl https://github.com/iden3/circom/releases/latest/download/circom-macos-amd64 -o /usr/local/bin/circom && chmod +x /usr/local/bin/circom
      # - name: Install yarn
      #   run: npm install -g yarn
      - name: Install dependencies
        run: npm install
      - name: Publish binaries
        run: npm run upload-binary
        env:
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
