[package]
name = "zk-regex-apis"
version = "1.1.6"
license = "MIT"
edition = "2018"
exclude = ["index.node"]
authors = [
    "Javier Su <javier.su.weijie@gmail.com>",
    "Kata Choi <kata.choi@gmail.com>",
    "Sora Suegami <suegamisora@gmail.com>",
    "Yush G <aayushg@mit.edu>",
]

[lib]
crate-type = ["rlib", "cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zk-regex-compiler = { path = "../compiler"}
fancy-regex = "0.11.0"
itertools = "0.10.3"
thiserror = "1.0.40"
serde_json = "1.0.95"


[dependencies.neon]
version = "0.10"
default-features = false
features = ["napi-6"]

[features]
default = ["export_neon_main"]
export_neon_main = []
